// <auto-generated />
using System;
using Katena.Domain;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

#nullable disable

namespace Katena.Migrations
{
    [DbContext(typeof(AppDbContext))]
    [Migration("20240313141626_doMigrationPls")]
    partial class doMigrationPls
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "8.0.2")
                .HasAnnotation("Relational:MaxIdentifierLength", 64);

            MySqlModelBuilderExtensions.AutoIncrementColumns(modelBuilder);

            modelBuilder.Entity("Katena.Domain.Entities.AnswersBase", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("char(36)");

                    b.Property<string>("Action")
                        .IsRequired()
                        .HasColumnType("longtext");

                    b.Property<string>("Reason")
                        .IsRequired()
                        .HasColumnType("longtext");

                    b.Property<string>("Type")
                        .IsRequired()
                        .HasColumnType("longtext");

                    b.Property<double>("Weight")
                        .HasColumnType("double");

                    b.HasKey("Id");

                    b.ToTable("Answers");

                    b.HasData(
                        new
                        {
                            Id = new Guid("cb83a258-54e1-4b2a-a58f-24fe95a357bc"),
                            Action = "Начну звонить соседям и выяснять у всех ли отключили",
                            Reason = "Может, кто-то знает причину отключения",
                            Type = "Hunter",
                            Weight = 0.0
                        },
                        new
                        {
                            Id = new Guid("03b5d02c-aa7f-47b9-8b80-4bd984ce7906"),
                            Action = "Начну искать телефоны снабжающих организаций и выяснять причину отключения",
                            Reason = "Надо вывалить на кого-то все зло, которое у меня накопилось",
                            Type = "Mentor",
                            Weight = 0.0
                        },
                        new
                        {
                            Id = new Guid("9102a12d-2845-4224-939e-913ab96524ab"),
                            Action = "Плевать, не велика проблема",
                            Reason = "Сейчас важнее не опаздать, а остальное -  мелочи",
                            Type = "Finder",
                            Weight = 0.0
                        },
                        new
                        {
                            Id = new Guid("e82f0359-d505-49f3-9292-f3877a9a844f"),
                            Action = "Это знак свыше, можно никуда сегодня не ходить, пойду спать дальше",
                            Reason = "Вот, наконец-то, повод отлежаться дома",
                            Type = "GoodMan",
                            Weight = 0.0
                        },
                        new
                        {
                            Id = new Guid("5ed2804d-bc6a-4296-b9a0-cf720271a18a"),
                            Action = "Накричу на него, заставлю извиняться",
                            Reason = "Если бы подобных людей в моей жизни было бы меньше, я бы чувствовал себя лучше",
                            Type = "Hunter",
                            Weight = 0.0
                        },
                        new
                        {
                            Id = new Guid("4c748f11-614c-4da8-97f2-eec8dc8ef989"),
                            Action = "Поеду домой переодеваться, а потом вернусь на вечеринку",
                            Reason = "Я всегда выгляжу идеально и должен быть примером для других",
                            Type = "Hunter",
                            Weight = 0.0
                        },
                        new
                        {
                            Id = new Guid("01786293-47e4-407e-9c24-66591aa9e099"),
                            Action = "Постараюсь, не привлекая внимания окружающих, удалить пятно подручными средствами, а если это не получится, продолжу веселиться вместе с пятном",
                            Reason = "Не думаю, что на подобной вечеринке мой канфуз будет сильно бросаться в глаза",
                            Type = "Mentor",
                            Weight = 0.0
                        },
                        new
                        {
                            Id = new Guid("6afb4539-1a1c-44d5-ab1e-c8b29fbc2ddc"),
                            Action = "Настроение испорчено, уеду с вечеринки",
                            Reason = "Никто не должен видеть меня в таком виде",
                            Type = "Finder",
                            Weight = 0.0
                        });
                });

            modelBuilder.Entity("Katena.Domain.Entities.QuestionBase", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("char(36)");

                    b.Property<string>("AnswerId")
                        .IsRequired()
                        .HasColumnType("longtext");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("longtext");

                    b.HasKey("Id");

                    b.ToTable("Questions");

                    b.HasData(
                        new
                        {
                            Id = new Guid("0dc6e45e-ba94-4f54-a59e-53caa1eea73c"),
                            AnswerId = "[\"cb83a258-54e1-4b2a-a58f-24fe95a357bc\",\"03b5d02c-aa7f-47b9-8b80-4bd984ce7906\",\"9102a12d-2845-4224-939e-913ab96524ab\",\"e82f0359-d505-49f3-9292-f3877a9a844f\"]",
                            Name = "Вы проснулись утром и поняли, что проспали сигнал будильника. Вы стремглав бежите в ванную и обнаруживаете, что в кране нет воды. Ни холодной, ни горячей. Ваши первые действия?"
                        },
                        new
                        {
                            Id = new Guid("2b8ad992-d4aa-4c3f-a65e-aaf036260807"),
                            AnswerId = "[\"5ed2804d-bc6a-4296-b9a0-cf720271a18a\",\"4c748f11-614c-4da8-97f2-eec8dc8ef989\",\"01786293-47e4-407e-9c24-66591aa9e099\",\"6afb4539-1a1c-44d5-ab1e-c8b29fbc2ddc\"]",
                            Name = "На корпоративе, к которому вы давно готовились, сосед случайно проливает на вас красное вино. Ваша первая реакция?"
                        },
                        new
                        {
                            Id = new Guid("2c517d36-d4db-4b02-b1c6-20b9c5eab29a"),
                            AnswerId = "[\"c407f32a-9fbf-486e-b744-c69f4961e58e\",\"0429066e-201f-4b2a-97fe-d15448bc4876\",\"6b39f0ec-0314-41c3-84f1-3b892bef6545\",\"1b08ffbf-6ae8-46b2-a058-10f742cbb3d4\"]",
                            Name = "Question from Jack Fresko?"
                        });
                });

            modelBuilder.Entity("Katena.Domain.Entities.QuestionPackBase", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("char(36)");

                    b.Property<string>("Description")
                        .IsRequired()
                        .HasColumnType("longtext");

                    b.Property<string>("Instructions")
                        .IsRequired()
                        .HasColumnType("longtext");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("longtext");

                    b.Property<string>("QuestionsIds")
                        .IsRequired()
                        .HasColumnType("longtext");

                    b.Property<string>("ResaultsId")
                        .IsRequired()
                        .HasColumnType("longtext");

                    b.HasKey("Id");

                    b.ToTable("Packs");

                    b.HasData(
                        new
                        {
                            Id = new Guid("0ed29a4b-ea2d-426d-add2-22753c7bf8cb"),
                            Description = "A good test to get to know yourself",
                            Instructions = "Think",
                            Name = "Personality test",
                            QuestionsIds = "[\"0dc6e45e-ba94-4f54-a59e-53caa1eea73c\",\"2b8ad992-d4aa-4c3f-a65e-aaf036260807\",\"2c517d36-d4db-4b02-b1c6-20b9c5eab29a\"]",
                            ResaultsId = "[\"959f07c9-5bd1-402c-9d29-c0cd3b5f954d\",\"cbed2409-359d-4425-9505-7434d6f75d79\",\"6662ee7c-34c8-4811-b3f3-ada6618dc47b\"]"
                        });
                });

            modelBuilder.Entity("Katena.Domain.Entities.ResaultsBase", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("char(36)");

                    b.Property<string>("Gender")
                        .IsRequired()
                        .HasColumnType("longtext");

                    b.Property<string>("Resault")
                        .IsRequired()
                        .HasColumnType("longtext");

                    b.Property<string>("Style")
                        .IsRequired()
                        .HasColumnType("longtext");

                    b.Property<string>("Type")
                        .IsRequired()
                        .HasColumnType("longtext");

                    b.HasKey("Id");

                    b.ToTable("Resaults");

                    b.HasData(
                        new
                        {
                            Id = new Guid("959f07c9-5bd1-402c-9d29-c0cd3b5f954d"),
                            Gender = "Male",
                            Resault = "Megamen",
                            Style = "Producer",
                            Type = "Mentor"
                        },
                        new
                        {
                            Id = new Guid("cbed2409-359d-4425-9505-7434d6f75d79"),
                            Gender = "Female",
                            Resault = "Megawomen",
                            Style = "Producer",
                            Type = "Mentor"
                        },
                        new
                        {
                            Id = new Guid("6662ee7c-34c8-4811-b3f3-ada6618dc47b"),
                            Gender = "Female",
                            Resault = "Strongwomen",
                            Style = "Entrepreneur",
                            Type = "Guardian"
                        });
                });

            modelBuilder.Entity("Katena.Domain.Entities.TextField", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("char(36)");

                    b.Property<string>("CodeWord")
                        .IsRequired()
                        .HasColumnType("longtext");

                    b.Property<DateTime>("DateAdded")
                        .HasColumnType("datetime(6)");

                    b.Property<string>("Text")
                        .IsRequired()
                        .HasColumnType("longtext");

                    b.Property<string>("Title")
                        .IsRequired()
                        .HasColumnType("longtext");

                    b.HasKey("Id");

                    b.ToTable("TextFields");

                    b.HasData(
                        new
                        {
                            Id = new Guid("63dc8fa6-07ae-4391-8916-e057f71239ce"),
                            CodeWord = "PageIndex",
                            DateAdded = new DateTime(2024, 3, 13, 14, 16, 25, 613, DateTimeKind.Utc).AddTicks(6890),
                            Text = "Содержание заполняется администратором",
                            Title = "Главная"
                        },
                        new
                        {
                            Id = new Guid("70bf165a-700a-4156-91c0-e83fce0a277f"),
                            CodeWord = "PageTests",
                            DateAdded = new DateTime(2024, 3, 13, 14, 16, 25, 613, DateTimeKind.Utc).AddTicks(6922),
                            Text = "Содержание заполняется администратором",
                            Title = "Тесты"
                        },
                        new
                        {
                            Id = new Guid("4aa76a4c-c59d-409a-84c1-06e6487a137a"),
                            CodeWord = "PageAbilities",
                            DateAdded = new DateTime(2024, 3, 13, 14, 16, 25, 613, DateTimeKind.Utc).AddTicks(6938),
                            Text = "Содержание заполняется администратором",
                            Title = "Возможности"
                        },
                        new
                        {
                            Id = new Guid("8eae0a63-8f52-4160-a14e-b405e431a13b"),
                            CodeWord = "PageContacts",
                            DateAdded = new DateTime(2024, 3, 13, 14, 16, 25, 613, DateTimeKind.Utc).AddTicks(6951),
                            Text = "Содержание заполняется администратором",
                            Title = "Контакты"
                        },
                        new
                        {
                            Id = new Guid("9b613a7d-49ee-4ce0-ba22-c161553584ac"),
                            CodeWord = "Sidebar",
                            DateAdded = new DateTime(2024, 3, 13, 14, 16, 25, 613, DateTimeKind.Utc).AddTicks(6963),
                            Text = "Содержание заполняется администратором",
                            Title = "Новости"
                        });
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityRole", b =>
                {
                    b.Property<string>("Id")
                        .HasColumnType("varchar(255)");

                    b.Property<string>("ConcurrencyStamp")
                        .IsConcurrencyToken()
                        .HasColumnType("longtext");

                    b.Property<string>("Name")
                        .HasMaxLength(256)
                        .HasColumnType("varchar(256)");

                    b.Property<string>("NormalizedName")
                        .HasMaxLength(256)
                        .HasColumnType("varchar(256)");

                    b.HasKey("Id");

                    b.HasIndex("NormalizedName")
                        .IsUnique()
                        .HasDatabaseName("RoleNameIndex");

                    b.ToTable("AspNetRoles", (string)null);

                    b.HasData(
                        new
                        {
                            Id = "e8ec6f61-f6d0-4b1d-bbe4-5910f862b2bd",
                            Name = "admin",
                            NormalizedName = "ADMIN"
                        });
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityRoleClaim<string>", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    MySqlPropertyBuilderExtensions.UseMySqlIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("ClaimType")
                        .HasColumnType("longtext");

                    b.Property<string>("ClaimValue")
                        .HasColumnType("longtext");

                    b.Property<string>("RoleId")
                        .IsRequired()
                        .HasColumnType("varchar(255)");

                    b.HasKey("Id");

                    b.HasIndex("RoleId");

                    b.ToTable("AspNetRoleClaims", (string)null);
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUser", b =>
                {
                    b.Property<string>("Id")
                        .HasColumnType("varchar(255)");

                    b.Property<int>("AccessFailedCount")
                        .HasColumnType("int");

                    b.Property<string>("ConcurrencyStamp")
                        .IsConcurrencyToken()
                        .HasColumnType("longtext");

                    b.Property<string>("Email")
                        .HasMaxLength(256)
                        .HasColumnType("varchar(256)");

                    b.Property<bool>("EmailConfirmed")
                        .HasColumnType("tinyint(1)");

                    b.Property<bool>("LockoutEnabled")
                        .HasColumnType("tinyint(1)");

                    b.Property<DateTimeOffset?>("LockoutEnd")
                        .HasColumnType("datetime(6)");

                    b.Property<string>("NormalizedEmail")
                        .HasMaxLength(256)
                        .HasColumnType("varchar(256)");

                    b.Property<string>("NormalizedUserName")
                        .HasMaxLength(256)
                        .HasColumnType("varchar(256)");

                    b.Property<string>("PasswordHash")
                        .HasColumnType("longtext");

                    b.Property<string>("PhoneNumber")
                        .HasColumnType("longtext");

                    b.Property<bool>("PhoneNumberConfirmed")
                        .HasColumnType("tinyint(1)");

                    b.Property<string>("SecurityStamp")
                        .HasColumnType("longtext");

                    b.Property<bool>("TwoFactorEnabled")
                        .HasColumnType("tinyint(1)");

                    b.Property<string>("UserName")
                        .HasMaxLength(256)
                        .HasColumnType("varchar(256)");

                    b.HasKey("Id");

                    b.HasIndex("NormalizedEmail")
                        .HasDatabaseName("EmailIndex");

                    b.HasIndex("NormalizedUserName")
                        .IsUnique()
                        .HasDatabaseName("UserNameIndex");

                    b.ToTable("AspNetUsers", (string)null);

                    b.HasData(
                        new
                        {
                            Id = "ef37a3c2-7c96-4405-a971-7abcc91ac333",
                            AccessFailedCount = 0,
                            ConcurrencyStamp = "7b390698-362d-44b3-93d2-8485de787c9b",
                            Email = "my@email.com",
                            EmailConfirmed = true,
                            LockoutEnabled = false,
                            NormalizedEmail = "MY@EMAIL.COM",
                            NormalizedUserName = "ADMIN",
                            PasswordHash = "AQAAAAIAAYagAAAAEGQOaYtY8jV9rQX9OVM0jewGrQsxmV15e37vMAeXghhHGizVf9H9Aih2crnSOICWgQ==",
                            PhoneNumberConfirmed = false,
                            SecurityStamp = "",
                            TwoFactorEnabled = false,
                            UserName = "admin"
                        });
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserClaim<string>", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    MySqlPropertyBuilderExtensions.UseMySqlIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("ClaimType")
                        .HasColumnType("longtext");

                    b.Property<string>("ClaimValue")
                        .HasColumnType("longtext");

                    b.Property<string>("UserId")
                        .IsRequired()
                        .HasColumnType("varchar(255)");

                    b.HasKey("Id");

                    b.HasIndex("UserId");

                    b.ToTable("AspNetUserClaims", (string)null);
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserLogin<string>", b =>
                {
                    b.Property<string>("LoginProvider")
                        .HasColumnType("varchar(255)");

                    b.Property<string>("ProviderKey")
                        .HasColumnType("varchar(255)");

                    b.Property<string>("ProviderDisplayName")
                        .HasColumnType("longtext");

                    b.Property<string>("UserId")
                        .IsRequired()
                        .HasColumnType("varchar(255)");

                    b.HasKey("LoginProvider", "ProviderKey");

                    b.HasIndex("UserId");

                    b.ToTable("AspNetUserLogins", (string)null);
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserRole<string>", b =>
                {
                    b.Property<string>("UserId")
                        .HasColumnType("varchar(255)");

                    b.Property<string>("RoleId")
                        .HasColumnType("varchar(255)");

                    b.HasKey("UserId", "RoleId");

                    b.HasIndex("RoleId");

                    b.ToTable("AspNetUserRoles", (string)null);

                    b.HasData(
                        new
                        {
                            UserId = "ef37a3c2-7c96-4405-a971-7abcc91ac333",
                            RoleId = "e8ec6f61-f6d0-4b1d-bbe4-5910f862b2bd"
                        });
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserToken<string>", b =>
                {
                    b.Property<string>("UserId")
                        .HasColumnType("varchar(255)");

                    b.Property<string>("LoginProvider")
                        .HasColumnType("varchar(255)");

                    b.Property<string>("Name")
                        .HasColumnType("varchar(255)");

                    b.Property<string>("Value")
                        .HasColumnType("longtext");

                    b.HasKey("UserId", "LoginProvider", "Name");

                    b.ToTable("AspNetUserTokens", (string)null);
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityRoleClaim<string>", b =>
                {
                    b.HasOne("Microsoft.AspNetCore.Identity.IdentityRole", null)
                        .WithMany()
                        .HasForeignKey("RoleId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserClaim<string>", b =>
                {
                    b.HasOne("Microsoft.AspNetCore.Identity.IdentityUser", null)
                        .WithMany()
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserLogin<string>", b =>
                {
                    b.HasOne("Microsoft.AspNetCore.Identity.IdentityUser", null)
                        .WithMany()
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserRole<string>", b =>
                {
                    b.HasOne("Microsoft.AspNetCore.Identity.IdentityRole", null)
                        .WithMany()
                        .HasForeignKey("RoleId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("Microsoft.AspNetCore.Identity.IdentityUser", null)
                        .WithMany()
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserToken<string>", b =>
                {
                    b.HasOne("Microsoft.AspNetCore.Identity.IdentityUser", null)
                        .WithMany()
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });
#pragma warning restore 612, 618
        }
    }
}
