// <auto-generated />
using System;
using Katena.Domain;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

#nullable disable

namespace Katena.Migrations
{
    [DbContext(typeof(AppDbContext))]
    partial class AppDbContextModelSnapshot : ModelSnapshot
    {
        protected override void BuildModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "8.0.3")
                .HasAnnotation("Relational:MaxIdentifierLength", 64);

            MySqlModelBuilderExtensions.AutoIncrementColumns(modelBuilder);

            modelBuilder.Entity("Katena.Domain.Entities.AnswersBase", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("char(36)");

                    b.Property<string>("Action")
                        .IsRequired()
                        .HasColumnType("longtext");

                    b.Property<int?>("Weight")
                        .IsRequired()
                        .HasColumnType("int");

                    b.Property<int?>("Weight1")
                        .IsRequired()
                        .HasColumnType("int");

                    b.Property<int?>("Weight10")
                        .IsRequired()
                        .HasColumnType("int");

                    b.Property<int?>("Weight11")
                        .IsRequired()
                        .HasColumnType("int");

                    b.Property<int?>("Weight12")
                        .IsRequired()
                        .HasColumnType("int");

                    b.Property<int?>("Weight13")
                        .IsRequired()
                        .HasColumnType("int");

                    b.Property<int?>("Weight14")
                        .IsRequired()
                        .HasColumnType("int");

                    b.Property<int?>("Weight15")
                        .IsRequired()
                        .HasColumnType("int");

                    b.Property<int?>("Weight2")
                        .IsRequired()
                        .HasColumnType("int");

                    b.Property<int?>("Weight3")
                        .IsRequired()
                        .HasColumnType("int");

                    b.Property<int?>("Weight4")
                        .IsRequired()
                        .HasColumnType("int");

                    b.Property<int?>("Weight5")
                        .IsRequired()
                        .HasColumnType("int");

                    b.Property<int?>("Weight6")
                        .IsRequired()
                        .HasColumnType("int");

                    b.Property<int?>("Weight7")
                        .IsRequired()
                        .HasColumnType("int");

                    b.Property<int?>("Weight8")
                        .IsRequired()
                        .HasColumnType("int");

                    b.Property<int?>("Weight9")
                        .IsRequired()
                        .HasColumnType("int");

                    b.Property<string>("reasonsId")
                        .IsRequired()
                        .HasColumnType("longtext");

                    b.Property<int?>("typeWeight1")
                        .IsRequired()
                        .HasColumnType("int");

                    b.Property<int?>("typeWeight2")
                        .IsRequired()
                        .HasColumnType("int");

                    b.Property<int?>("typeWeight3")
                        .IsRequired()
                        .HasColumnType("int");

                    b.Property<int?>("typeWeight4")
                        .IsRequired()
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.ToTable("Answers");

                    b.HasData(
                        new
                        {
                            Id = new Guid("cb83a258-54e1-4b2a-a58f-24fe95a357bc"),
                            Action = "Начну звонить соседям и выяснять у всех ли отключили",
                            Weight = 0,
                            Weight1 = 0,
                            Weight10 = 0,
                            Weight11 = 0,
                            Weight12 = 0,
                            Weight13 = 0,
                            Weight14 = 0,
                            Weight15 = 0,
                            Weight2 = 0,
                            Weight3 = 0,
                            Weight4 = 0,
                            Weight5 = 0,
                            Weight6 = 0,
                            Weight7 = 0,
                            Weight8 = 0,
                            Weight9 = 0,
                            reasonsId = "[\"f70fca13-268b-4e2e-9906-066b455d2081\",\"c2ea7376-d1fb-466d-91b3-a6efb2fb0063\",\"661db458-5cea-431e-b8ba-6a91ed2854a6\"]",
                            typeWeight1 = 0,
                            typeWeight2 = 0,
                            typeWeight3 = 0,
                            typeWeight4 = 0
                        },
                        new
                        {
                            Id = new Guid("03b5d02c-aa7f-47b9-8b80-4bd984ce7906"),
                            Action = "Начну искать телефоны снабжающих организаций и выяснять причину отключения",
                            Weight = 0,
                            Weight1 = 0,
                            Weight10 = 0,
                            Weight11 = 0,
                            Weight12 = 0,
                            Weight13 = 0,
                            Weight14 = 0,
                            Weight15 = 0,
                            Weight2 = 0,
                            Weight3 = 0,
                            Weight4 = 0,
                            Weight5 = 0,
                            Weight6 = 0,
                            Weight7 = 0,
                            Weight8 = 0,
                            Weight9 = 0,
                            reasonsId = "[\"f70fca13-268b-4e2e-9906-066b455d2081\",\"c2ea7376-d1fb-466d-91b3-a6efb2fb0063\",\"661db458-5cea-431e-b8ba-6a91ed2854a6\"]",
                            typeWeight1 = 0,
                            typeWeight2 = 0,
                            typeWeight3 = 0,
                            typeWeight4 = 0
                        },
                        new
                        {
                            Id = new Guid("9102a12d-2845-4224-939e-913ab96524ab"),
                            Action = "Плевать, не велика проблема",
                            Weight = 0,
                            Weight1 = 0,
                            Weight10 = 0,
                            Weight11 = 0,
                            Weight12 = 0,
                            Weight13 = 0,
                            Weight14 = 0,
                            Weight15 = 0,
                            Weight2 = 0,
                            Weight3 = 0,
                            Weight4 = 0,
                            Weight5 = 0,
                            Weight6 = 0,
                            Weight7 = 0,
                            Weight8 = 0,
                            Weight9 = 0,
                            reasonsId = "[\"f70fca13-268b-4e2e-9906-066b455d2081\",\"c2ea7376-d1fb-466d-91b3-a6efb2fb0063\",\"661db458-5cea-431e-b8ba-6a91ed2854a6\"]",
                            typeWeight1 = 0,
                            typeWeight2 = 0,
                            typeWeight3 = 0,
                            typeWeight4 = 0
                        },
                        new
                        {
                            Id = new Guid("e82f0359-d505-49f3-9292-f3877a9a844f"),
                            Action = "Это знак свыше, можно никуда сегодня не ходить, пойду спать дальше",
                            Weight = 0,
                            Weight1 = 0,
                            Weight10 = 0,
                            Weight11 = 0,
                            Weight12 = 0,
                            Weight13 = 0,
                            Weight14 = 0,
                            Weight15 = 0,
                            Weight2 = 0,
                            Weight3 = 0,
                            Weight4 = 0,
                            Weight5 = 0,
                            Weight6 = 0,
                            Weight7 = 0,
                            Weight8 = 0,
                            Weight9 = 0,
                            reasonsId = "[\"f70fca13-268b-4e2e-9906-066b455d2081\",\"c2ea7376-d1fb-466d-91b3-a6efb2fb0063\",\"661db458-5cea-431e-b8ba-6a91ed2854a6\"]",
                            typeWeight1 = 0,
                            typeWeight2 = 0,
                            typeWeight3 = 0,
                            typeWeight4 = 0
                        },
                        new
                        {
                            Id = new Guid("5ed2804d-bc6a-4296-b9a0-cf720271a18a"),
                            Action = "Накричу на него, заставлю извиняться",
                            Weight = 0,
                            Weight1 = 0,
                            Weight10 = 0,
                            Weight11 = 0,
                            Weight12 = 0,
                            Weight13 = 0,
                            Weight14 = 0,
                            Weight15 = 0,
                            Weight2 = 0,
                            Weight3 = 0,
                            Weight4 = 0,
                            Weight5 = 0,
                            Weight6 = 0,
                            Weight7 = 0,
                            Weight8 = 0,
                            Weight9 = 0,
                            reasonsId = "[\"f70fca13-268b-4e2e-9906-066b455d2081\",\"c2ea7376-d1fb-466d-91b3-a6efb2fb0063\",\"661db458-5cea-431e-b8ba-6a91ed2854a6\"]",
                            typeWeight1 = 0,
                            typeWeight2 = 0,
                            typeWeight3 = 0,
                            typeWeight4 = 0
                        },
                        new
                        {
                            Id = new Guid("4c748f11-614c-4da8-97f2-eec8dc8ef989"),
                            Action = "Поеду домой переодеваться, а потом вернусь на вечеринку",
                            Weight = 0,
                            Weight1 = 0,
                            Weight10 = 0,
                            Weight11 = 0,
                            Weight12 = 0,
                            Weight13 = 0,
                            Weight14 = 0,
                            Weight15 = 0,
                            Weight2 = 0,
                            Weight3 = 0,
                            Weight4 = 0,
                            Weight5 = 0,
                            Weight6 = 0,
                            Weight7 = 0,
                            Weight8 = 0,
                            Weight9 = 0,
                            reasonsId = "[\"f70fca13-268b-4e2e-9906-066b455d2081\",\"c2ea7376-d1fb-466d-91b3-a6efb2fb0063\",\"661db458-5cea-431e-b8ba-6a91ed2854a6\"]",
                            typeWeight1 = 0,
                            typeWeight2 = 0,
                            typeWeight3 = 0,
                            typeWeight4 = 0
                        },
                        new
                        {
                            Id = new Guid("01786293-47e4-407e-9c24-66591aa9e099"),
                            Action = "Постараюсь, не привлекая внимания окружающих, удалить пятно подручными средствами, а если это не получится, продолжу веселиться вместе с пятном",
                            Weight = 0,
                            Weight1 = 0,
                            Weight10 = 0,
                            Weight11 = 0,
                            Weight12 = 0,
                            Weight13 = 0,
                            Weight14 = 0,
                            Weight15 = 0,
                            Weight2 = 0,
                            Weight3 = 0,
                            Weight4 = 0,
                            Weight5 = 0,
                            Weight6 = 0,
                            Weight7 = 0,
                            Weight8 = 0,
                            Weight9 = 0,
                            reasonsId = "[\"f70fca13-268b-4e2e-9906-066b455d2081\",\"c2ea7376-d1fb-466d-91b3-a6efb2fb0063\",\"661db458-5cea-431e-b8ba-6a91ed2854a6\"]",
                            typeWeight1 = 0,
                            typeWeight2 = 0,
                            typeWeight3 = 0,
                            typeWeight4 = 0
                        },
                        new
                        {
                            Id = new Guid("6afb4539-1a1c-44d5-ab1e-c8b29fbc2ddc"),
                            Action = "Настроение испорчено, уеду с вечеринки",
                            Weight = 0,
                            Weight1 = 0,
                            Weight10 = 0,
                            Weight11 = 0,
                            Weight12 = 0,
                            Weight13 = 0,
                            Weight14 = 0,
                            Weight15 = 0,
                            Weight2 = 0,
                            Weight3 = 0,
                            Weight4 = 0,
                            Weight5 = 0,
                            Weight6 = 0,
                            Weight7 = 0,
                            Weight8 = 0,
                            Weight9 = 0,
                            reasonsId = "[\"f70fca13-268b-4e2e-9906-066b455d2081\",\"c2ea7376-d1fb-466d-91b3-a6efb2fb0063\",\"661db458-5cea-431e-b8ba-6a91ed2854a6\"]",
                            typeWeight1 = 0,
                            typeWeight2 = 0,
                            typeWeight3 = 0,
                            typeWeight4 = 0
                        });
                });

            modelBuilder.Entity("Katena.Domain.Entities.NewsBase", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("char(36)");

                    b.Property<string>("Text")
                        .IsRequired()
                        .HasColumnType("longtext");

                    b.Property<string>("Title")
                        .IsRequired()
                        .HasColumnType("longtext");

                    b.Property<string>("TitleImagePath")
                        .HasColumnType("longtext");

                    b.HasKey("Id");

                    b.ToTable("News");

                    b.HasData(
                        new
                        {
                            Id = new Guid("c8be520d-1590-41b1-9376-7a8d2c05f797"),
                            Text = "Теперь можно добавлять картинки!",
                            Title = "Новость дня",
                            TitleImagePath = ""
                        });
                });

            modelBuilder.Entity("Katena.Domain.Entities.QuestionBase", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("char(36)");

                    b.Property<string>("AnswerId")
                        .IsRequired()
                        .HasColumnType("longtext");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("longtext");

                    b.HasKey("Id");

                    b.ToTable("Questions");

                    b.HasData(
                        new
                        {
                            Id = new Guid("0dc6e45e-ba94-4f54-a59e-53caa1eea73c"),
                            AnswerId = "[\"cb83a258-54e1-4b2a-a58f-24fe95a357bc\",\"03b5d02c-aa7f-47b9-8b80-4bd984ce7906\",\"9102a12d-2845-4224-939e-913ab96524ab\",\"e82f0359-d505-49f3-9292-f3877a9a844f\"]",
                            Name = "Вы проснулись утром и поняли, что проспали сигнал будильника. Вы стремглав бежите в ванную и обнаруживаете, что в кране нет воды. Ни холодной, ни горячей. Ваши первые действия?"
                        },
                        new
                        {
                            Id = new Guid("2b8ad992-d4aa-4c3f-a65e-aaf036260807"),
                            AnswerId = "[\"5ed2804d-bc6a-4296-b9a0-cf720271a18a\",\"4c748f11-614c-4da8-97f2-eec8dc8ef989\",\"01786293-47e4-407e-9c24-66591aa9e099\",\"6afb4539-1a1c-44d5-ab1e-c8b29fbc2ddc\"]",
                            Name = "На корпоративе, к которому вы давно готовились, сосед случайно проливает на вас красное вино. Ваша первая реакция?"
                        });
                });

            modelBuilder.Entity("Katena.Domain.Entities.QuestionPackBase", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("char(36)");

                    b.Property<string>("Description")
                        .IsRequired()
                        .HasColumnType("longtext");

                    b.Property<string>("Instructions")
                        .IsRequired()
                        .HasColumnType("longtext");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("longtext");

                    b.Property<string>("QuestionsIds")
                        .HasColumnType("longtext");

                    b.Property<string>("ResaultsId")
                        .HasColumnType("longtext");

                    b.Property<string>("TitleImagePath")
                        .HasColumnType("longtext");

                    b.HasKey("Id");

                    b.ToTable("Packs");

                    b.HasData(
                        new
                        {
                            Id = new Guid("0ed29a4b-ea2d-426d-add2-22753c7bf8cb"),
                            Description = "A good test to get to know yourself",
                            Instructions = "Think",
                            Name = "Personality test",
                            QuestionsIds = "[\"0dc6e45e-ba94-4f54-a59e-53caa1eea73c\",\"2b8ad992-d4aa-4c3f-a65e-aaf036260807\"]",
                            ResaultsId = "[\"959f07c9-5bd1-402c-9d29-c0cd3b5f954d\",\"cbed2409-359d-4425-9505-7434d6f75d79\",\"6662ee7c-34c8-4811-b3f3-ada6618dc47b\"]"
                        });
                });

            modelBuilder.Entity("Katena.Domain.Entities.ReasonBase", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("char(36)");

                    b.Property<string>("Reason")
                        .IsRequired()
                        .HasColumnType("longtext");

                    b.Property<int?>("Weight")
                        .IsRequired()
                        .HasColumnType("int");

                    b.Property<int?>("Weight1")
                        .IsRequired()
                        .HasColumnType("int");

                    b.Property<int?>("Weight10")
                        .IsRequired()
                        .HasColumnType("int");

                    b.Property<int?>("Weight11")
                        .IsRequired()
                        .HasColumnType("int");

                    b.Property<int?>("Weight12")
                        .IsRequired()
                        .HasColumnType("int");

                    b.Property<int?>("Weight13")
                        .IsRequired()
                        .HasColumnType("int");

                    b.Property<int?>("Weight14")
                        .IsRequired()
                        .HasColumnType("int");

                    b.Property<int?>("Weight2")
                        .IsRequired()
                        .HasColumnType("int");

                    b.Property<int?>("Weight3")
                        .IsRequired()
                        .HasColumnType("int");

                    b.Property<int?>("Weight4")
                        .IsRequired()
                        .HasColumnType("int");

                    b.Property<int?>("Weight5")
                        .IsRequired()
                        .HasColumnType("int");

                    b.Property<int?>("Weight6")
                        .IsRequired()
                        .HasColumnType("int");

                    b.Property<int?>("Weight7")
                        .IsRequired()
                        .HasColumnType("int");

                    b.Property<int?>("Weight8")
                        .IsRequired()
                        .HasColumnType("int");

                    b.Property<int?>("Weight9")
                        .IsRequired()
                        .HasColumnType("int");

                    b.Property<int?>("typeWeight1")
                        .IsRequired()
                        .HasColumnType("int");

                    b.Property<int?>("typeWeight10")
                        .IsRequired()
                        .HasColumnType("int");

                    b.Property<int?>("typeWeight2")
                        .IsRequired()
                        .HasColumnType("int");

                    b.Property<int?>("typeWeight3")
                        .IsRequired()
                        .HasColumnType("int");

                    b.Property<int?>("typeWeight4")
                        .IsRequired()
                        .HasColumnType("int");

                    b.Property<int?>("typeWeight5")
                        .IsRequired()
                        .HasColumnType("int");

                    b.Property<int?>("typeWeight6")
                        .IsRequired()
                        .HasColumnType("int");

                    b.Property<int?>("typeWeight7")
                        .IsRequired()
                        .HasColumnType("int");

                    b.Property<int?>("typeWeight8")
                        .IsRequired()
                        .HasColumnType("int");

                    b.Property<int?>("typeWeight9")
                        .IsRequired()
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.ToTable("Reasons");

                    b.HasData(
                        new
                        {
                            Id = new Guid("f70fca13-268b-4e2e-9906-066b455d2081"),
                            Reason = "Reason",
                            Weight = 0,
                            Weight1 = 0,
                            Weight10 = 0,
                            Weight11 = 0,
                            Weight12 = 0,
                            Weight13 = 0,
                            Weight14 = 0,
                            Weight2 = 0,
                            Weight3 = 0,
                            Weight4 = 0,
                            Weight5 = 0,
                            Weight6 = 0,
                            Weight7 = 0,
                            Weight8 = 0,
                            Weight9 = 0,
                            typeWeight1 = 0,
                            typeWeight10 = 0,
                            typeWeight2 = 0,
                            typeWeight3 = 0,
                            typeWeight4 = 0,
                            typeWeight5 = 0,
                            typeWeight6 = 0,
                            typeWeight7 = 0,
                            typeWeight8 = 0,
                            typeWeight9 = 0
                        },
                        new
                        {
                            Id = new Guid("c2ea7376-d1fb-466d-91b3-a6efb2fb0063"),
                            Reason = "Second reason",
                            Weight = 0,
                            Weight1 = 0,
                            Weight10 = 0,
                            Weight11 = 0,
                            Weight12 = 0,
                            Weight13 = 0,
                            Weight14 = 0,
                            Weight2 = 0,
                            Weight3 = 0,
                            Weight4 = 0,
                            Weight5 = 0,
                            Weight6 = 0,
                            Weight7 = 0,
                            Weight8 = 0,
                            Weight9 = 0,
                            typeWeight1 = 0,
                            typeWeight10 = 0,
                            typeWeight2 = 0,
                            typeWeight3 = 0,
                            typeWeight4 = 0,
                            typeWeight5 = 0,
                            typeWeight6 = 0,
                            typeWeight7 = 0,
                            typeWeight8 = 0,
                            typeWeight9 = 0
                        },
                        new
                        {
                            Id = new Guid("661db458-5cea-431e-b8ba-6a91ed2854a6"),
                            Reason = "Third reason",
                            Weight = 0,
                            Weight1 = 0,
                            Weight10 = 0,
                            Weight11 = 0,
                            Weight12 = 0,
                            Weight13 = 0,
                            Weight14 = 0,
                            Weight2 = 0,
                            Weight3 = 0,
                            Weight4 = 0,
                            Weight5 = 0,
                            Weight6 = 0,
                            Weight7 = 0,
                            Weight8 = 0,
                            Weight9 = 0,
                            typeWeight1 = 0,
                            typeWeight10 = 0,
                            typeWeight2 = 0,
                            typeWeight3 = 0,
                            typeWeight4 = 0,
                            typeWeight5 = 0,
                            typeWeight6 = 0,
                            typeWeight7 = 0,
                            typeWeight8 = 0,
                            typeWeight9 = 0
                        });
                });

            modelBuilder.Entity("Katena.Domain.Entities.ResaultsBase", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("char(36)");

                    b.Property<string>("Gender")
                        .IsRequired()
                        .HasColumnType("longtext");

                    b.Property<string>("Resault")
                        .IsRequired()
                        .HasColumnType("longtext");

                    b.Property<string>("Style")
                        .IsRequired()
                        .HasColumnType("longtext");

                    b.Property<string>("Type")
                        .IsRequired()
                        .HasColumnType("longtext");

                    b.HasKey("Id");

                    b.ToTable("Resaults");

                    b.HasData(
                        new
                        {
                            Id = new Guid("959f07c9-5bd1-402c-9d29-c0cd3b5f954d"),
                            Gender = "Male",
                            Resault = "Megamen",
                            Style = "Producer",
                            Type = "Mentor"
                        },
                        new
                        {
                            Id = new Guid("cbed2409-359d-4425-9505-7434d6f75d79"),
                            Gender = "Female",
                            Resault = "Megawomen",
                            Style = "Producer",
                            Type = "Mentor"
                        },
                        new
                        {
                            Id = new Guid("6662ee7c-34c8-4811-b3f3-ada6618dc47b"),
                            Gender = "Female",
                            Resault = "Strongwomen",
                            Style = "Entrepreneur",
                            Type = "Guardian"
                        });
                });

            modelBuilder.Entity("Katena.Domain.Entities.TextField", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("char(36)");

                    b.Property<string>("CodeWord")
                        .IsRequired()
                        .HasColumnType("longtext");

                    b.Property<DateTime>("DateAdded")
                        .HasColumnType("datetime(6)");

                    b.Property<string>("Text")
                        .IsRequired()
                        .HasColumnType("longtext");

                    b.Property<string>("Title")
                        .IsRequired()
                        .HasColumnType("longtext");

                    b.Property<string>("TitleImagePath")
                        .HasColumnType("longtext");

                    b.HasKey("Id");

                    b.ToTable("TextFields");

                    b.HasData(
                        new
                        {
                            Id = new Guid("63dc8fa6-07ae-4391-8916-e057f71239ce"),
                            CodeWord = "PageIndex",
                            DateAdded = new DateTime(2024, 4, 18, 6, 33, 3, 859, DateTimeKind.Utc).AddTicks(1779),
                            Text = "Содержание заполняется администратором",
                            Title = "Главная"
                        },
                        new
                        {
                            Id = new Guid("70bf165a-700a-4156-91c0-e83fce0a277f"),
                            CodeWord = "PageTests",
                            DateAdded = new DateTime(2024, 4, 18, 6, 33, 3, 859, DateTimeKind.Utc).AddTicks(1826),
                            Text = "Содержание заполняется администратором",
                            Title = "Тесты"
                        },
                        new
                        {
                            Id = new Guid("4aa76a4c-c59d-409a-84c1-06e6487a137a"),
                            CodeWord = "PageAbilities",
                            DateAdded = new DateTime(2024, 4, 18, 6, 33, 3, 859, DateTimeKind.Utc).AddTicks(1854),
                            Text = "Содержание заполняется администратором",
                            Title = "Возможности"
                        },
                        new
                        {
                            Id = new Guid("8eae0a63-8f52-4160-a14e-b405e431a13b"),
                            CodeWord = "PageContacts",
                            DateAdded = new DateTime(2024, 4, 18, 6, 33, 3, 859, DateTimeKind.Utc).AddTicks(1882),
                            Text = "Содержание заполняется администратором",
                            Title = "Контакты"
                        });
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityRole", b =>
                {
                    b.Property<string>("Id")
                        .HasColumnType("varchar(255)");

                    b.Property<string>("ConcurrencyStamp")
                        .IsConcurrencyToken()
                        .HasColumnType("longtext");

                    b.Property<string>("Name")
                        .HasMaxLength(256)
                        .HasColumnType("varchar(256)");

                    b.Property<string>("NormalizedName")
                        .HasMaxLength(256)
                        .HasColumnType("varchar(256)");

                    b.HasKey("Id");

                    b.HasIndex("NormalizedName")
                        .IsUnique()
                        .HasDatabaseName("RoleNameIndex");

                    b.ToTable("AspNetRoles", (string)null);

                    b.HasData(
                        new
                        {
                            Id = "e8ec6f61-f6d0-4b1d-bbe4-5910f862b2bd",
                            Name = "admin",
                            NormalizedName = "ADMIN"
                        });
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityRoleClaim<string>", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    MySqlPropertyBuilderExtensions.UseMySqlIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("ClaimType")
                        .HasColumnType("longtext");

                    b.Property<string>("ClaimValue")
                        .HasColumnType("longtext");

                    b.Property<string>("RoleId")
                        .IsRequired()
                        .HasColumnType("varchar(255)");

                    b.HasKey("Id");

                    b.HasIndex("RoleId");

                    b.ToTable("AspNetRoleClaims", (string)null);
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUser", b =>
                {
                    b.Property<string>("Id")
                        .HasColumnType("varchar(255)");

                    b.Property<int>("AccessFailedCount")
                        .HasColumnType("int");

                    b.Property<string>("ConcurrencyStamp")
                        .IsConcurrencyToken()
                        .HasColumnType("longtext");

                    b.Property<string>("Email")
                        .HasMaxLength(256)
                        .HasColumnType("varchar(256)");

                    b.Property<bool>("EmailConfirmed")
                        .HasColumnType("tinyint(1)");

                    b.Property<bool>("LockoutEnabled")
                        .HasColumnType("tinyint(1)");

                    b.Property<DateTimeOffset?>("LockoutEnd")
                        .HasColumnType("datetime(6)");

                    b.Property<string>("NormalizedEmail")
                        .HasMaxLength(256)
                        .HasColumnType("varchar(256)");

                    b.Property<string>("NormalizedUserName")
                        .HasMaxLength(256)
                        .HasColumnType("varchar(256)");

                    b.Property<string>("PasswordHash")
                        .HasColumnType("longtext");

                    b.Property<string>("PhoneNumber")
                        .HasColumnType("longtext");

                    b.Property<bool>("PhoneNumberConfirmed")
                        .HasColumnType("tinyint(1)");

                    b.Property<string>("SecurityStamp")
                        .HasColumnType("longtext");

                    b.Property<bool>("TwoFactorEnabled")
                        .HasColumnType("tinyint(1)");

                    b.Property<string>("UserName")
                        .HasMaxLength(256)
                        .HasColumnType("varchar(256)");

                    b.HasKey("Id");

                    b.HasIndex("NormalizedEmail")
                        .HasDatabaseName("EmailIndex");

                    b.HasIndex("NormalizedUserName")
                        .IsUnique()
                        .HasDatabaseName("UserNameIndex");

                    b.ToTable("AspNetUsers", (string)null);

                    b.HasData(
                        new
                        {
                            Id = "ef37a3c2-7c96-4405-a971-7abcc91ac333",
                            AccessFailedCount = 0,
                            ConcurrencyStamp = "26f0f05e-1e9e-4589-8ef8-a8e5d1bd7a4f",
                            Email = "my@email.com",
                            EmailConfirmed = true,
                            LockoutEnabled = false,
                            NormalizedEmail = "MY@EMAIL.COM",
                            NormalizedUserName = "ADMIN",
                            PasswordHash = "AQAAAAIAAYagAAAAEEzwAQ4G2V8xJKDX1dOpm0N6qIYXfw0gueWFP9EUYHv87L1AnJnRc1MjiaHwMu97vA==",
                            PhoneNumberConfirmed = false,
                            SecurityStamp = "",
                            TwoFactorEnabled = false,
                            UserName = "admin"
                        });
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserClaim<string>", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    MySqlPropertyBuilderExtensions.UseMySqlIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("ClaimType")
                        .HasColumnType("longtext");

                    b.Property<string>("ClaimValue")
                        .HasColumnType("longtext");

                    b.Property<string>("UserId")
                        .IsRequired()
                        .HasColumnType("varchar(255)");

                    b.HasKey("Id");

                    b.HasIndex("UserId");

                    b.ToTable("AspNetUserClaims", (string)null);
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserLogin<string>", b =>
                {
                    b.Property<string>("LoginProvider")
                        .HasColumnType("varchar(255)");

                    b.Property<string>("ProviderKey")
                        .HasColumnType("varchar(255)");

                    b.Property<string>("ProviderDisplayName")
                        .HasColumnType("longtext");

                    b.Property<string>("UserId")
                        .IsRequired()
                        .HasColumnType("varchar(255)");

                    b.HasKey("LoginProvider", "ProviderKey");

                    b.HasIndex("UserId");

                    b.ToTable("AspNetUserLogins", (string)null);
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserRole<string>", b =>
                {
                    b.Property<string>("UserId")
                        .HasColumnType("varchar(255)");

                    b.Property<string>("RoleId")
                        .HasColumnType("varchar(255)");

                    b.HasKey("UserId", "RoleId");

                    b.HasIndex("RoleId");

                    b.ToTable("AspNetUserRoles", (string)null);

                    b.HasData(
                        new
                        {
                            UserId = "ef37a3c2-7c96-4405-a971-7abcc91ac333",
                            RoleId = "e8ec6f61-f6d0-4b1d-bbe4-5910f862b2bd"
                        });
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserToken<string>", b =>
                {
                    b.Property<string>("UserId")
                        .HasColumnType("varchar(255)");

                    b.Property<string>("LoginProvider")
                        .HasColumnType("varchar(255)");

                    b.Property<string>("Name")
                        .HasColumnType("varchar(255)");

                    b.Property<string>("Value")
                        .HasColumnType("longtext");

                    b.HasKey("UserId", "LoginProvider", "Name");

                    b.ToTable("AspNetUserTokens", (string)null);
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityRoleClaim<string>", b =>
                {
                    b.HasOne("Microsoft.AspNetCore.Identity.IdentityRole", null)
                        .WithMany()
                        .HasForeignKey("RoleId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserClaim<string>", b =>
                {
                    b.HasOne("Microsoft.AspNetCore.Identity.IdentityUser", null)
                        .WithMany()
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserLogin<string>", b =>
                {
                    b.HasOne("Microsoft.AspNetCore.Identity.IdentityUser", null)
                        .WithMany()
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserRole<string>", b =>
                {
                    b.HasOne("Microsoft.AspNetCore.Identity.IdentityRole", null)
                        .WithMany()
                        .HasForeignKey("RoleId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("Microsoft.AspNetCore.Identity.IdentityUser", null)
                        .WithMany()
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserToken<string>", b =>
                {
                    b.HasOne("Microsoft.AspNetCore.Identity.IdentityUser", null)
                        .WithMany()
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });
#pragma warning restore 612, 618
        }
    }
}
